volumes:
  xpra_volume_2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra81:
    image: hieuxpra
    mem_limit: 1g
    hostname: xpra
    container_name: hieuxfce81
    restart: always
    volumes:
    - xpra_volume_2:/usr/share/xpra
    ports:
    - 81:80
    expose:
    - '9876'
    memswap_limit: 22g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
