volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra92:
    image: hieuxpra
    mem_limit: 1g
    hostname: xpra
    container_name: hieuxfce92
    restart: always
    volumes:
    - xpra_volume:/usr/share/xpra
    expose:
    - '9876'
    memswap_limit: 22g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  nginx92:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./htpasswd_folder/nginx92.htpasswd:/etc/nginx/.htpasswd
    image: nginx
    depends_on:
    - xpra92
    container_name: nginx92
    ports:
    - 92:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
