volumes:
  xpra_volume_2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra101:
    image: hieuxpra
    mem_limit: 1g
    hostname: xpra
    container_name: hieuxfce101
    restart: always
    volumes:
    - xpra_volume_2:/usr/share/xpra
    expose:
    - '9876'
    memswap_limit: 22g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  nginx101:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./htpasswd_folder/nginx101.htpasswd:/etc/nginx/.htpasswd
    - xpra_volume_2:/usr/share/xpra
    image: nginx
    depends_on:
    - xpra101
    container_name: nginx101
    ports:
    - 101:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 8G
