volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra89:
    image: hieuxpra
    mem_limit: 1g
    hostname: xpra
    container_name: hieuxfce89
    restart: always
    volumes:
    - xpra_volume:/usr/share/xpra
    expose:
    - '9876'
    memswap_limit: 22g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  nginx89:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./htpasswd_folder/nginx89.htpasswd:/etc/nginx/.htpasswd
    image: nginx
    depends_on:
    - xpra89
    container_name: nginx89
    ports:
    - 89:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
