volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra91:
    image: hieuxpra
    mem_limit: 1g
    hostname: xpra
    container_name: hieuxfce91
    restart: always
    volumes:
    - xpra_volume:/usr/share/xpra
    expose:
    - '9876'
    memswap_limit: 22g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  nginx91:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    image: nginx
    depends_on:
    - xpra91
    container_name: nginx91
    ports:
    - 91:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
