volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra:
    image: hieuxpra
    container_name: hieuxfce1
    hostname: xpra
    restart: always
    expose: &id002
    - '9876'
    volumes: &id001
    - xpra_volume:/usr/share/xpra
    deploy: &id003
      resources:
        limits:
          cpus: '1'
          memory: 1G
    mem_limit: 1g
    memswap_limit: 22g
  nginx87:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./htpasswd_folder/nginx87.htpasswd:/etc/nginx/.htpasswd
    image: nginx
    depends_on: xpra87
    container_name: nginx87
    ports:
    - 87:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  xpra87:
    image: hieuxpra
    mem_limit: 1g
    hostname: xpra
    container_name: hieuxfce87
    restart: always
    volumes: *id001
    expose: *id002
    memswap_limit: 22g
    deploy: *id003
