services:
  xpra:
    image: hieutestxfce2
    container_name: hieuxfce2
    hostname: xpra
    restart: always
    expose:
      - '9876'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    mem_limit: 1g
    memswap_limit: 22g
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "83:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - xpra
  auth_changer:
    image: alpine
    volumes:
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./change_auth.sh:/change_auth.sh
      - ./auth_credentials.txt:/auth_credentials.txt
      - ./init_auth_changer.sh:/init_auth_changer.sh
    command: sh /init_auth_changer.sh