services:
  xpra:
    image: hieuxpra
#    container_name: hieuxfce2
    hostname: xpra
    restart: always
    ports:
      - 82:876
    expose:
    - '9876'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
    mem_limit: 3g
    memswap_limit: 22g
  nginx1:
    image: nginx
    container_name: nginx1
    ports:
    - 82:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./htpasswd_folder/nginx91.htpasswd:/etc/nginx/.htpasswd
    depends_on:
    - xpra
  auth_changer:
    image: alpine
    volumes:
    - ./nginx/nginx91.htpasswd:/etc/nginx/nginx91.htpasswd
    - ./change_auth.sh:/change_auth.sh
    - ./auth_credentials.txt:/auth_credentials.txt
    - ./init_auth_changer.sh:/init_auth_changer.sh
    command: sh /init_auth_changer.sh
