volumes:
  xpra_volume_2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra:
    image: hieuxpra
    container_name: hieuxfce1234567
    hostname: xpra
    restart: always
    expose:
      - '9876'
    ports:
      - 81:9876
    volumes:
      - xpra_volume_2:/usr/share/xpra
    mem_limit: 1g
    memswap_limit: 22g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
